language: go
install: true
before_script:
 - chmod +x ./travis_scripts/ftp_deploy.sh
 - echo -e "Host ssh.strato.de\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script: 
 - echo "Skip build"
after_success:
 - openssl aes-256-cbc -K $encrypted_efbac4de9d64_key -iv $encrypted_efbac4de9d64_iv -in ./travis_scripts/id_rsa.enc -out ./travis_scripts/id_rsa -d
 - ls -la travis_scripts
 - ./travis_scripts/ftp_deploy.sh