BaseUrl = "http://p-reports.com/"
languageCode = "en-us"
title = "PReports | projects at a glance"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Frederik Reifschneider"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "favicon.ico"



	# Navigation
	[params.navigation]
		brand = "PReports"

	#portfolio = "Testimonials"

		[[params.navigation.links]]
			title = "About"
			href = "about"

		[[params.navigation.links]]
			title = "Features"
			href = "services"

		[[params.navigation.links]]
			title = "Testimonials"
			href = "testimonials"

		[[params.navigation.links]]
			title = "Packages"
			href = "pricing"

		[[params.navigation.links]]
			title = "Contact"
			href = "contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "PReports"
		subtitle   = "projects at a glance"
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "Create and manage weekly IT project reports!"
		description = "Create your weekly project report in a few minutes. Concentrate on the content instead of copying the same slides every week, just to update a few lines of texts. See how PReports lets you create your reports in a breeze."
		buttonText  = "Try the demo!"
		link = "https://preports.herokuapp.com"


	# Service section
	[params.services]
		headline = "Features"

        [[params.services.list]]
            icon = "fa-sitemap"
            title = "Organized"
            description = "Organize your reports on a weekly basis. Create a new report in seconds."

        [[params.services.list]]
			icon = "fa-search"
			title = "Search"
			description = "Easily find the report you are looking for."

		[[params.services.list]]
            icon = "fa-rocket"
            title = "Fast"
            description = "Edit on the go and let the auto save do the rest."

        [[params.services.list]]
            icon = "fa-share-alt"
            title = "Share"
            description = "Finished the report? Just send your colleaques the link or notify them via mail or slack."

        [[params.services.list]]
            icon = "fa-clone"
            title = "Copy"
            description = "New week, new report. Duplicate last weeks report with just two clicks."

        [[params.services.list]]
            icon = "fa-mobile"
            title = "Mobile"
            description = "Designed with mobility in mind. Edit your reports on every device."

        [[params.services.list]]
            icon = "fa-lock"
            title = "Security"
            description = "Supports CAS out of the box. Plugin for other auth systems possible."

        [[params.services.list]]
            icon = "fa-github"
            title = "OpenSource"
            description = "PReports is open source. Feel free to grab and modify it."


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        buttonText = "Close"

    # Testimonials

    [params.testimonials]
    	headline = "What others say"
    	icon = "fa-comment"

    	[[params.testimonials.list]]
    		company = "Bisnode Germany"
    		person = "Jürgen Schlesinger, Head of Development"
    		statement = "PReports cuts right to the point - getting my weekly project reports done as fast as possible. It helps me keeping an overview of my projects state and makes it easy to share with colleagues. No more copy and paste of slides."

    	[[params.testimonials.list]]
    		company = "Awesome Inc"
    		person = "Your name"
    		statement = "Are you using PReports? We would be happy to share your statement."


    # Pricing section
	[params.pricing]
		headline    = "Packages"

	[params.pricing.free]
		title = "Free tier"
		description = "PReports is open source. You are free to use PReports and modify it. Just grab the code from github and set it up."

	[params.pricing.premium]	
		title = "Premium tier"
		description = "Please contact us if you have additionl feature requirements or need support for setup. Based on your requirements we will make you a great offer."

    # Aside section
	[params.aside]
		headline = "Get it now!"

		[params.aside.button]
			text = "Fork it on Github"
			link = "//github.com/karazy/preports"
			icon = "fa-github"

	# Contact section
	[params.contact]
		headline = "Need support?"
		description = "Please contact us."
		email = "frederik.reifschneider@gmail.com"
		linkedin_url = "https://de.linkedin.com/in/frederik-reifschneider-8587bb1b"
		linkedin_name = "Frederik Reifschneider"